INSERT INTO categories (product_id, name)
VALUES (1, 'Disney'),
(2, 'Marvel'),
(3, 'Harry Potter'),
(4, 'Disney'),
(5, 'Marvel'),
(6, 'Disney'),
(7, 'TV Shows'),
(8, 'Disney'),
(9, 'Marvel'),
(10, 'Harry Potter'),
(11, 'Disney'),
(12, 'Disney'),
(13, 'Marvel'),
(14, 'Harry Potter'),
(15, 'Marvel'),
(16, 'Films'),
(17, 'Marvel'),
(18, 'Harry Potter'),
(19, 'Disney'),
(20, 'TV Shows'),
(21, 'TV Shows')
